# Generated by Django 5.2.1 on 2025-05-19 11:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=tinymce.models.HTMLField(),
        ),
    ]
