# Generated by Django 5.2.1 on 2025-05-21 19:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='story',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
