# Generated by Django 5.2.1 on 2025-05-22 11:18

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_hero_alter_post_description_alter_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
