# Generated by Django 5.2.1 on 2025-05-22 12:05

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
