# Generated by Django 5.2.1 on 2025-05-23 15:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='story',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
